/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Catppuccin Mocha (dark)
        mocha: {
          base: '#1e1e2e',
          mantle: '#181825',
          crust: '#11111b',
          text: '#cdd6f4',
          subtext0: '#a6adc8',
          subtext1: '#bac2de',
          surface0: '#313244',
          surface1: '#45475a',
          surface2: '#585b70',
          overlay0: '#6c7086',
          overlay1: '#7f849c',
          overlay2: '#9399b2',
          blue: '#89b4fa',
          lavender: '#b4befe',
          sapphire: '#74c7ec',
          sky: '#89dceb',
          teal: '#94e2d5',
          green: '#a6e3a1',
          yellow: '#f9e2af',
          peach: '#fab387',
          maroon: '#eba0ac',
          red: '#f38ba8',
          mauve: '#cba6f7',
          pink: '#f5c2e7',
          flamingo: '#f2cdcd',
          rosewater: '#f5e0dc',
        },
        // Catppuccin Latte (light)
        latte: {
          base: '#eff1f5',
          mantle: '#e6e9ef',
          crust: '#dce0e8',
          text: '#4c4f69',
          subtext0: '#6c6f85',
          subtext1: '#5c5f77',
          surface0: '#ccd0da',
          surface1: '#bcc0cc',
          surface2: '#acb0be',
          overlay0: '#9ca0b0',
          overlay1: '#8c8fa1',
          overlay2: '#7c7f93',
          blue: '#1e66f5',
          lavender: '#7287fd',
          sapphire: '#209fb5',
          sky: '#04a5e5',
          teal: '#179299',
          green: '#40a02b',
          yellow: '#df8e1d',
          peach: '#fe640b',
          maroon: '#e64553',
          red: '#d20f39',
          mauve: '#8839ef',
          pink: '#ea76cb',
          flamingo: '#dd7878',
          rosewater: '#dc8a78',
        },
      },
      fontFamily: {
        mono: [
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      typography: () => ({
        catppuccin: {
          css: {
            '--tw-prose-body': 'var(--color-text)',
            '--tw-prose-headings': 'var(--color-text)',
            '--tw-prose-lead': 'var(--color-subtext)',
            '--tw-prose-links': 'var(--color-accent)',
            '--tw-prose-bold': 'var(--color-text)',
            '--tw-prose-counters': 'var(--color-subtext)',
            '--tw-prose-bullets': 'var(--color-overlay)',
            '--tw-prose-hr': 'var(--color-border)',
            '--tw-prose-quotes': 'var(--color-subtext)',
            '--tw-prose-quote-borders': 'var(--color-accent)',
            '--tw-prose-captions': 'var(--color-subtext)',
            '--tw-prose-code': 'var(--color-mauve)',
            '--tw-prose-pre-code': 'var(--color-text)',
            '--tw-prose-pre-bg': 'var(--color-surface)',
            '--tw-prose-th-borders': 'var(--color-border)',
            '--tw-prose-td-borders': 'var(--color-border)',
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
